#!/bin/bash
if [ -s  $1 ]; then

	vi $1
else 
	touch $1
	chmod a+x $1 
	echo "#include <stdlib.h>" > $1
	echo "#include \"main.h\"" >> $1
	echo "#include <stdio.h>" >> $1
	echo "/**
 * main - Entry point of the program.
 *
 * Description: Prints a string to the console.
 *
 * Return: Always 0 (success).
 */" >> $1
	echo "int main(void)" >> $1
	echo "{" >> $1
	echo "return (0);" >> $1
	echo "}" >> $1
	
fi

