#!/bin/bash

filename="$1"  # Get the filename from the command line argument

# Check if the file already exists
if [ -e "$filename" ]; then
    # Check if the file starts with #!/bin/bash
    if ! head -n 1 "$filename" | grep -q "^#!/bin/bash"; then
        sed -i '1i#!/bin/bash' "$filename"  # Add #!/bin/bash to the first line
    fi
else
    echo "#!/bin/bash" > "$filename"  # Create the file with #!/bin/bash
fi

vi "$filename"
chmod u+x "$filename"

